"""Static structural dictionaries, including deterministic compiler vocabulary."""

NODE_TYPES = [
    "character",
    "speaker",
    "organization",
    "location",
    "item",
    "term",
    "concept",
    "quest",
    "quest_state",
    "quest_action",
    "quest_node",
    "scene",
    "conversation",
    "dialogue_line",
    "player_choice",
    "narration",
    "cutscene",
    "voice_reference",
    "media_asset",
    "arc",
    "chapter",
    "major_event",
    "event",
    "action",
    "area",
    "asset_reference",
    "audio_event",
    "branch",
    "caption",
    "chat_partner",
    "cutscene_variant",
    "flow",
    "flow_state",
    "fragment_memory",
    "localization_file",
    "map_block",
    "music_subtitle",
    "nested_action",
    "npc",
    "phone_message",
    "plot_guest",
    "plot_step",
    "quest_branch_page",
    "quest_review_line",
    "quest_review_node",
    "quest_time_point",
    "random_plot",
    "random_plot_reference",
    "random_plot_trigger",
    "short_message",
    "source_reference",
    "subtitle",
    "talk_item",
    "video_qte",
]
RELATION_TYPES = [
    "CONTAINS",
    "NEXT",
    "CHOICE_TO",
    "REFERENCES",
    "INVOLVES",
    "OCCURS_AT",
    "MEMBER_OF",
    "TRAINED_BY",
    "RAISED_BY",
    "CAUSES",
    "CAUSED_BY",
    "LEADS_TO",
    "REVEALS",
    "EXPLAINS",
    "FORESHADOWS",
    "branch_target",
    "checks_quest_node",
    "choice_branch",
    "condition_references_quest",
    "condition_slot",
    "decomposes_into",
    "contains_action",
    "contains_nested_action",
    "has_branch",
    "has_chat_partner",
    "has_condition_branch",
    "has_flow_state",
    "has_plot_step",
    "has_quest_node",
    "has_reference_config",
    "has_review_node",
    "has_speaker",
    "has_variant",
    "has_video_qte",
    "has_voice_reference",
    "jumps_to_talk",
    "listens_for_quest",
    "next_authored_plot_step",
    "next_authored_talk",
    "next_source_action",
    "parent_of",
    "plays_cutscene",
    "plays_sequence_asset",
    "posts_audio_event",
    "presents_choice",
    "presents_scene",
    "presents_talk_item",
    "references_area",
    "references_character",
    "references_asset",
    "references_flow_state",
    "references_item",
    "references_map_block",
    "references_npc",
    "references_quest",
    "references_quest_node",
    "references_video_package",
    "requires_quest",
    "review_successor",
    "sequence_transition",
    "spoken_by",
    "starts_at_review_node",
    "triggers_random_plot",
    "uses_audio_event",
    "uses_caption",
    "uses_plot_reference",
    "within_area",
]
EVENT_TYPES = [
    "meeting",
    "conversation",
    "battle",
    "reveal",
    "death",
    "sacrifice",
    "departure",
    "arrival",
    "discovery",
]
FILE_TYPES = [
    "raw_archive",
    "raw_json",
    "raw_jsonl",
    "audio_wem",
    "audio_wav",
    "audio_ogg",
    "audio_opus",
    "audio_mp3",
    "video_game",
    "video_mp4",
    "video_webm",
    "subtitle_srt",
    "subtitle_vtt",
    "image",
    "thumbnail",
    "sequence",
    "unknown",
]
LOCALES = {
    "en": "English",
    "zh-Hans": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "ja": "Japanese",
    "ko": "Korean",
    "ru": "Russian",
    "de": "German",
    "fr": "French",
    "es": "Spanish",
    "pt": "Portuguese",
    "vi": "Vietnamese",
    "th": "Thai",
    "id": "Indonesian",
}
STATUSES = {
    "import": ["pending", "running", "succeeded", "failed", "cancelled"],
    "processing": ["pending", "running", "succeeded", "failed", "cancelled"],
    "semantic": ["clean", "dirty", "processing", "failed", "needs_review"],
    "storage": ["available", "unavailable", "verified"],
    "document": ["draft", "published", "archived"],
}
