/** Application defaults. VITE_API_* environment variables still override API URLs. */
export const APP_SETTINGS = {
  api: { defaultBase: '/api', defaultDocsUrl: 'http://localhost:8000/docs' },
  storage: {
    locale: 'wuwa-locale',
    mapFilters: 'atlas-map-filters',
    narrative: 'solaris-atlas:narrative-preferences:v1',
    guestPlayerTitle: 'solaris-atlas:guest-player-title:v1',
  },
  narrative: {
    nameMode: 'nickname',
    colorMode: 'accent',
    customColor: '#9BD9C0',
    voiceLanguage: 'en',
    preferredRover: 'ask',
  },
  limits: {
    catalogPage: 24,
    catalogSearch: 50,
    search: 60,
    explanationSearch: 8,
    inlineDialogueSearch: 8,
    relatedNodes: 100,
    transcript: 2000,
    relatedPreview: 18,
    biographyPreviewCharacters: 260,
  },
  presentation: {
    feedbackDurationMs: 2500,
    skeletonCount: 8,
    cardStaggerMs: 25,
    cardStaggerMaxIndex: 12,
  },
  storyAgent: {
    pageSize: 20,
    refreshMs: 10000,
    extraSteps: 16,
    outputRecoveryMinTokens: 16384,
    maxOutputTokens: 32000,
  },
  map: {
    minZoom: -6,
    overviewZoomOutLevels: 1,
    maxZoom: 3,
    initialZoom: -2,
    detailMinZoom: -1,
    markerFocusMinZoom: 2,
    compactViewportWidth: 760,
    markerFocusVerticalOffset: 0.25,
    locationMaxZoom: 1,
    clusterZoomStep: 1,
    markerZoomStep: 2,
    clusterSplitZoom: 2,
    clusterCellPixels: 42,
    closeClusterCellPixels: 20,
    markerSize: 30,
    clusterSize: 32,
    initialFitPadding: 25,
    locationFitPadding: 35,
    surfaceOpacityPercent: 30,
    signedUrlRefreshMs: 45 * 60 * 1000,
    markerPageSize: 5000,
    listPageSize: 60,
    regionLabelCharacters: 3,
    defaultGameMapId: 8,
    panes: [
      ['surface-preview', 200],
      ['surface-detail', 220],
      ['floor-preview', 240],
      ['floor-detail', 260],
    ],
    // Coordinate contract with extracted tiles; change together with the importer.
    worldUnitsPerTile: 85000,
    tilePixels: 256,
    tileNativeZoom: 0,
  },
} as const;
