# This module re-exports mapped classes to populate metadata for Alembic and callers.
# ruff: noqa: F401
from wuwa_story.db.models.auth import (
    AuthSession,
    Identity,
    OAuthState,
    PendingLink,
    PendingRegistration,
    User,
)
from wuwa_story.db.models.content import Document, DocumentHead, DocumentReference
from wuwa_story.db.models.core import (
    NPC,
    AudioEvent,
    Character,
    Concept,
    Conversation,
    ConversationMember,
    Cutscene,
    DialogueLine,
    Item,
    Location,
    MediaAsset,
    Narration,
    Organization,
    PhoneMessage,
    PlayerChoice,
    Quest,
    QuestAction,
    QuestNode,
    QuestState,
    Speaker,
    SpeakerEntityLink,
    Term,
    VoiceReference,
)
from wuwa_story.db.models.graph import Edge, EdgeEvidence, Node, NodeRevision, NodeType
from wuwa_story.db.models.i18n import (
    Locale,
    LocalizationContent,
    LocalizationKey,
    LocalizationValue,
)
from wuwa_story.db.models.maps import MapMarker, MapTile, TileMap
from wuwa_story.db.models.ontology import (
    EventType,
    NodeTag,
    RelationAlias,
    RelationCandidate,
    RelationType,
    Tag,
    TagAlias,
    TagCandidate,
)
from wuwa_story.db.models.ops import (
    AIModel,
    Dependency,
    GameRelease,
    ImportRun,
    ProcessingRun,
    Processor,
)
from wuwa_story.db.models.raw import SourceFile, SourceRecord
from wuwa_story.db.models.search import (
    DialogueChunk,
    DialogueChunkEmbedding,
    EmbeddingModel,
    EntityAlias,
    NodeEmbedding,
    RelationEmbedding,
    SearchDocument,
    TagEmbedding,
)
from wuwa_story.db.models.status import StatusType
from wuwa_story.db.models.storage import (
    FileLocation,
    FileObject,
    FileReference,
    FileType,
    FileVariant,
)
from wuwa_story.db.models.story import (
    Claim,
    ClaimEvidence,
    Event,
    Scene,
    StoryContainer,
    StoryMembership,
)

__all__ = [
    "AuthSession",
    "Identity",
    "OAuthState",
    "PendingLink",
    "PendingRegistration",
    "User",
    "Document",
    "DocumentHead",
    "DocumentReference",
    "NPC",
    "AudioEvent",
    "Character",
    "Concept",
    "Conversation",
    "ConversationMember",
    "Cutscene",
    "DialogueLine",
    "Item",
    "Location",
    "MediaAsset",
    "Narration",
    "Organization",
    "PhoneMessage",
    "PlayerChoice",
    "Quest",
    "QuestAction",
    "QuestNode",
    "QuestState",
    "Speaker",
    "SpeakerEntityLink",
    "Term",
    "VoiceReference",
    "Edge",
    "EdgeEvidence",
    "Node",
    "NodeRevision",
    "NodeType",
    "Locale",
    "LocalizationKey",
    "LocalizationContent",
    "LocalizationValue",
    "EventType",
    "NodeTag",
    "RelationAlias",
    "RelationCandidate",
    "RelationType",
    "Tag",
    "TagAlias",
    "TagCandidate",
    "AIModel",
    "Dependency",
    "GameRelease",
    "ImportRun",
    "ProcessingRun",
    "Processor",
    "SourceFile",
    "SourceRecord",
    "DialogueChunk",
    "DialogueChunkEmbedding",
    "EmbeddingModel",
    "EntityAlias",
    "NodeEmbedding",
    "RelationEmbedding",
    "SearchDocument",
    "TagEmbedding",
    "StatusType",
    "FileLocation",
    "FileObject",
    "FileReference",
    "FileType",
    "FileVariant",
    "Claim",
    "ClaimEvidence",
    "Event",
    "Scene",
    "StoryContainer",
    "StoryMembership",
]
